# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repository_manifest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='manifest_id',
        ),
    ]
