# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161110_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_repository', models.BooleanField(default=True)),
                ('verify_data', models.BooleanField(default=False, help_text='Verify all data cryptographically (slow)')),
                ('check_archives', models.BooleanField(default=True)),
                ('check_only_new_archives', models.BooleanField(default=False, help_text='Check only archives added since the last check')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_configs', to='core.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='CheckJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Job')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CheckConfig')),
            ],
            bases=('core.job',),
        ),
        migrations.RenameField(
            model_name='job',
            old_name='db_state',
            new_name='state',
        ),
    ]
