# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_job_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='repository_id',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', help_text='32 bytes in hex', max_length=200, verbose_name='Repository ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.Repository'),
        ),
        migrations.RemoveField(
            model_name='repository',
            name='id',
        ),
        migrations.AlterField(
            model_name='repository',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
